### ISSUE TITLE
Add a global.json file so that any new projects use the released .Net sdk

### ISSUE THREAD

**Issue by SeanFarrow** [andrewlock/PwnedPasswords#11]
It would probably be good to add a global.json file so that the latest released .net sdk is used and not any preview anyone cloning the repo might have installed.

**Comment by andrewlock** [comment]
Nice idea! It would be best if we could pin any 2.x (for now) global.json rather than necessarily having to be 2.2 - when you don't have the right SDK installed you always got horrible unclear error messages (not sure if that's changed) so would be good to avoid that. I'm fairly sure you can have wildcards in the SDK name

**Comment by SeanFarrow** [comment]
It’s something I’d need to look in to but will do that over the next day or so.

**Comment by SeanFarrow** [comment]
According to 
[here](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
A full version number is required.

I'm therefore proposing we support .net sdk 2.1.603.

I don't think we are using any .Net 2.2 features from what I've seen, but feel free to correct me.
