### ISSUE TITLE
Do new record being added at the end of file? 

### ISSUE THREAD

**Issue by zohaibcs** [andrewlock/PwnedPasswords#25]
I wanted to confirm the update strategy. Do new records being added at the end of the file? 
For example I downloaded a file and inserted it into my database. Now after some time, I want to update my database. I download the file again but want to add the latest records instead of dumping all the data from DB and insert again.

**Comment by SeanFarrow** [comment]
The current client does not have an abstraction for querying using anything other than the API, so I’m not sure what you are asking for help with?
Thanks,
Sean.
From: Zohab Hassan ***@***.***>
Sent: Monday, June 5, 2023 5:29 PM
To: andrewlock/PwnedPasswords ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [andrewlock/PwnedPasswords] Do new record being added at the end of file? (Issue #25)


I wanted to confirm the update strategy. Do new records being added at the end of the file?
For example I downloaded a file and inserted it into my database. Now after some time, I want to update my database. I download the file again but want to add the latest records instead of dumping all the data from DB and insert again.

**Comment by zohaibcs** [comment]
I got it resolved. Thanks for help
